name: 'Wait for status checks'
description: 'Waits for GitHub one or more status check to complete for the specified commit'
inputs:
  status-checks:
    description: 'Name of the GitHub status check'
    required: true
  time-interval:
    description: 'Time interval in seconds between checks on the status. default 15 seconds'
    required: false
    default: '15'
  wait-time:
    description: 'Total time to wait before the action timesout, default 240 seconds'
    required: false
    default: '240'
  github-token:
    description: 'The GitHub token used to create an authenticated client'
    default: ${{ github.token }}
    required: false
  repository:
    description: 'Name of the GitHub repository eg: github/octocat, default: github.repository'
    required: false
    default: ${{ github.repository }}
  sha:
    description: 'Commit sha to check for the status. default github.sha'
    required: false
    default: ${{ github.sha }}
outputs:
  conclusion:
    description: 'The conclusion of the action, can be success, failure or timed_out'  
runs:
  using: 'docker'
  image: 'Dockerfile'
  args:
    - ${{ inputs.github-token }}
    - ${{ inputs.repository }}
    - ${{ inputs.sha }}
    - ${{ inputs.status-checks }}
    - ${{ inputs.time-interval }}
    - ${{ inputs.wait-time }}
