name: 'Wait for status checks'
description: 'Waits for a GitHub status check to complete.'
inputs:
  github-token:
    description: The GitHub token used to create an authenticated client
    default: ${{ github.token }}
    required: false
  status-check-name:
    description: 'Name of the GitHub status check'
    required: true
    default: ''
  repository:
    description: 'Name of the GitHub repository eg: github/octocat, default: github.repository'
    required: false
    default: ''
  sha:
    description: 'Commit sha to check for the status. default github.sha'
    required: false
    default: ${{ github.sha }}
  multi-line-text:
    description: 'A multi line test'
    required: false
    default: ''
outputs:
  time:
    description: 'The time the action was completed'
runs:
  using: 'docker'
  image: 'Dockerfile'
  args:
    - ${{ inputs.github-token }}
    - ${{ inputs.repository }}
    - ${{ inputs.sha }}
    - ${{ inputs.status-check-name }}
    - ${{ inputs.multi-line-text }}
