name: 'Wait for status checks'
description: 'Waits for a GitHub status check to complete.'
inputs:
  status-check-name:
    description: 'Name of the GitHub status check'
    required: true
    default: ''
  repository:
    description: 'Name of the GitHub repository eg: github/octocat, default: github.repository'
    required: false
    default: ''
  sha:
    description: 'The commit sha to check for the status. default github.sha'
    required: false
    default: ''
outputs:
  time:
    description: 'The time the action was completed'
runs:
  using: 'docker'
  image: 'Dockerfile'
  args:
    - ${{ inputs.status-check-name }}
    - ${{ inputs.repository }}
    - ${{ inputs.sha }}
