name: 'Wait for status checks'
description: 'Waits for GitHub one or more status check to complete for the specified commit'
inputs:
  github-token:
    description: 'The GitHub token used to create an authenticated client'
    default: ${{ github.token }}
    required: false
  status-checks:
    description: 'Name of the GitHub status check'
    required: true
    default: ''
  repository:
    description: 'Name of the GitHub repository eg: github/octocat, default: github.repository'
    required: false
    default: ${{ github.repository }}
  sha:
    description: 'Commit sha to check for the status. default github.sha'
    required: false
    default: ${{ github.sha }}
outputs:
  time:
    description: 'The time the action was completed'
  outcome:
    description: 'The outcome of the action'  
runs:
  using: 'docker'
  image: 'Dockerfile'
  args:
    - ${{ inputs.github-token }}
    - ${{ inputs.repository }}
    - ${{ inputs.sha }}
    - ${{ inputs.status-checks }}
