name: Build

on:
  push:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v2
       
    - name: Setup .NET Core
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 3.1.301

    - name: Build
      run: |
        dotnet restore
        dotnet build --configuration Release --no-restore --output ./app

    - name: Build & push Docker image
      run: |
        docker build -f ./.github/Dockerfile -t ${{ env.DOCKER_IMAGE }} .
        docker login -u $DOCKERHUB_USERNAME -p $DOCKERHUB_PASSWORD
        docker push ${{ env.DOCKER_IMAGE }}
      env:
        DOCKERHUB_USERNAME: ${{ secrets.DOCKERHUB_USERNAME }}
        DOCKERHUB_PASSWORD: ${{ secrets.DOCKERHUB_PASSWORD }}
        DOCKER_IMAGE: ${{ format('vigneshmsft/wait-for-status-check-action-{0}', github.sha )}}
