on: [push]

jobs:
  test_wait_status_check:
    runs-on: ubuntu-latest
    name: Test job for vigneshmsft/wait-for-status-check-action
    steps:
    - name: Checkout
      uses: actions/checkout@v2

    - name: Wait for status check
      id: wait_for_status_check
      #uses: vigneshmsft/wait-for-status-check-action@v0.1.0
      uses: ./
      with:
        github-token: ${{ secrets.TEST_TOKEN }}
        repository: DFE-Digital/find-teacher-training
        sha: 53cbfa183856adc470a9f6ba8a59860f2359f8d7
        status-checks: |
          'smoke-tests-qa'
          'smoke-tests-production'

    - name: Get the output time
      run: echo "The time was ${{ steps.wait_for_status_check.outputs.time }}"
