on: [push]

jobs:
  hello_world_job:
    runs-on: ubuntu-latest
    name: A job to say hello
    steps:
    - name: Wait for status check
      id: wait_for_status_check
      uses: vigneshmsft/wait-for-status-check-action@v1
      with:
        status-check-name: 'Octocat'
    
    - name: Get the output time
      run: echo "The time was ${{ steps.wait_for_status_check.outputs.time }}"
